[package]
name = "paperbark"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23"
itertools = "0.10.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tui = "0.18"
